solve exercises of arrays
AnastasiyaYS/study pull request #1
Opened 2020-04-17 21:46 UTC by AnastasiyaYS

2020-04-18 19:21 UTC, pn-y requested changes

2020-04-18 19:21 UTC, pn-y commented on test/exercise/arrays/solution.rb
> +        array.map { |item| item.positive? ? array.max : item }
max вызывается на каждую итерацию. Это работает, но это очень неотпимально.
max надо реализовать самому.

2020-04-20 10:21 UTC, pn-y requested changes

2020-04-20 10:21 UTC, pn-y commented on test/exercise/arrays/solution.rb
> +          else iter.call(array_part[middle_index + 1, middle_index], index + middle_index + 1)
В этой строке вызов функции выглядит как условие, чем вводит в заблуждение

2020-04-20 17:00 UTC, artempartos requested changes

2020-04-20 17:00 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = lambda do |full_array|
вынеси реализацию max  в отедльную функцию. Постарайся упростить код, выглядит слишком сложно

2020-04-23 08:34 UTC, devality approved these changes

2020-04-23 09:28 UTC, merged