Fp
AnastasiyaYS/study pull request #2
Opened 2020-04-19 09:03 UTC by AnastasiyaYS

2020-04-20 10:27 UTC, pn-y requested changes

2020-04-20 10:27 UTC, pn-y commented on test/exercise/fp/solution.rb
> +        filtered_films.reduce(0) { |i_letter_count, film| i_letter_count + (film['name'].count 'и') }
https://github.com/rubocop-hq/ruby-style-guide#method-invocation-parentheses
Вместо того чтоб обернуть `и` в скобки зачем то обернут вест вызов count над именем.

2020-04-20 17:01 UTC, artempartos requested changes

2020-04-20 17:01 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = lambda do |full_array|
почему этот Pr содержит изменения предыдущей ветки? они тебе нужны? Нет, должно быть только решение задачи FP

2020-04-23 08:39 UTC, devality approved these changes

2020-04-23 09:29 UTC, merged