Fp2
AnastasiyaYS/study pull request #3
Opened 2020-04-19 20:03 UTC by AnastasiyaYS

2020-04-20 17:03 UTC, artempartos requested changes

2020-04-20 17:03 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = lambda do |full_array|
опять изменения предыдущих веток

2020-04-20 17:03 UTC, artempartos commented on test/exercise/fp2/solution.rb
> +        my_each(&(->(item) { result << func.call(item) }))
такая реализация будет работать
Но обычно когда ты объявляешь что то в начале, потом в итерации что-то делаешь а потом возвращаешь что насобирала - это верный признак что надо использовать reduce.
Давай заиспользуем уже готовую функцию my_reduce и через нее реализуем my_map и my_compact

2020-04-23 08:49 UTC, devality approved these changes

2020-04-23 09:29 UTC, merged